### ISSUE TITLE
关于在复现实验时出现的一些问题

### ISSUE THREAD

**Issue by derekshiii** [HiLab-git/UPL-SFDA#2]
作者你好，在复现实验时出现如下问题，烦请解答。
按照readme文档配置后，使用mms数据集测试时发现dice和assd极低，使用wandb在test_run.py跟踪后结果如图
![image](https://github.com/HiLab-git/UPL-SFDA/assets/102472253/847aa753-6d57-498e-beba-94a0f6888a0c)
结果并不收敛且跳动较大。该结果是原始数据集裁剪时间轴后训练的，使用的原模型是MMS_model-source.pth。部分域适应结果如图：
![结果拼图1](https://github.com/HiLab-git/UPL-SFDA/assets/102472253/f0d1a157-1706-43ab-acea-019ec960e584)
想请教下您对于这个结果有什么建议，可以提升最终结果。
此外，还有一个疑问： MMS数据集裁剪时间轴后为3D图像，为何在示例源码中train2d_source.cfg则是使用该数据集？
感激不尽！！
祝科研顺利

**Comment by JianghaoWu** [comment]
due to different devices, it is recommended that you use a small learning rate, such as 1 * 10 ^ -5

**Comment by JianghaoWu** [comment]
the network is 2D unet, and the data is 3D volume, it is right. Due to the big stickiness between slices, so we convert it into 2D in the training process ( you don't process the data into 2D ), you just do it according to  train2d_source.cfg.

**Comment by derekshiii** [comment]
Thank you so much for your reply!! I will try it later.

**Comment by lkfiean** [comment]
@derekshiii 你好，请问你复现出文中的指标了吗
